### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ElGoogleElgoog** [TurtleShroom/Super_Mario_Mod#1]
Really sorry to have to post this here but I got blocked from the WTWSMS one.

Re: being Maelgwn, 
Yes, should have made that clear, sorry.

**Comment by TurtleShroom** [comment]
Hello!

Thank you for contacting me. Loup is still very bitter at you, and from what he says about "private conversations" and your ranting and whining in them, he is wholly convinced that you want no part in this Mod.

I can relay your message to him, but he seems adament on excluding you.

**Comment by TurtleShroom** [comment]
@AzimuthBlast 

Maelgwyn, if you want to speak to me on this Mod in the future, please contact me at https://github.com/TurtleShroom/WtWSMS/issues instead of here. This is for the Mario Mod alone.

I will close this thread now. Please refer to https://github.com/TurtleShroom/WtWSMS/issues from here on out.
